### ISSUE TITLE
Frictionless onboarding example: explorer shows no change in state

### ISSUE THREAD

**Issue by eliotstock** [ithacaxyz/odyssey#10]
Stepping through your integrated wallet operations here...

https://www.ithaca.xyz/updates/odyssey#frictionless-l2-onboarding

... and following along on your block explorer here...

https://odyssey-explorer.ithaca.xyz/

I see no change in state for the address I created at all. still have 0 test ETH, no tokens and no transactions ten minutes after doing these things in the dApp.

My address is 0x08e8ac91ebefb3f021c44043ae2558f47aadcfdb, in case it helps.

**Comment by mattsse** [comment]
sorry, the sponsor account ran out of funds over night...

topped it up again, please try again!

thanks for trying it out!

**Comment by eliotstock** [comment]
Ok so in that case the bug is that the dApp tells the user all is well when in fact the tx has not executed. I mean, it's just a demo, but still. First impressions and all that.

**Comment by eliotstock** [comment]
Also, I am now in a state where trying again doesn't work.

I clicked "remove" for the existing wallet, then "create". I got Passkey-authed, but nothing happened. The "Your wallet" panel is still in the state of not having a wallet, with the "create" button still there.

The swap panel is still blocked on "Create a wallet to swap EXP".
