### ISSUE TITLE
Set up GitHub labels

### ISSUE THREAD

**Issue by onbjerg** [ithacaxyz/odyssey#2]

**Comment by jenpaff** [comment]
> No description provided.

@onbjerg can do, which labels do you need?

**Comment by onbjerg** [comment]
I think just in the same style as reth, so one for each component (prob just A-node, A-wallet, A-walltime, ?), labels for what kind of feature or task it is, e.g. C-perf, C-debt etc

**Comment by onbjerg** [comment]
lgtm
