### ISSUE TITLE
Integrate automated kurtosis setup 

### ISSUE THREAD

**Issue by jenpaff** [ithacaxyz/odyssey#34]
## Describe the feature
 
We use an [optimism-package fork](https://github.com/paradigmxyz/optimism-package) for testing with kurtosis, goal of this feature would be to update the setup and integrate with automated tests in the ci

## Additional context 

Tasks include:  
 - work towards removing the need for a fork (move changes upstream or at least open a github issue and document why its needed)
 - test scripts to run against kurtosis and deployment 
 - integrate kurtosis in ci workflow with automated test scripts

**Comment by onbjerg** [comment]
Closed in #47
