### ISSUE TITLE
Use next free nonce in `wallet_sendTransaction`

### ISSUE THREAD

**Issue by onbjerg** [ithacaxyz/odyssey#39]
Currently we use the highest nonce in the pool or on disk, whichever is higher, in `wallet_sendTransaction`, but this can lead to nonce gaps, which ultimately leads the sequencer-sponsored txs to back up and get stuck. Instead we should use the next free nonce.

Depends on https://github.com/paradigmxyz/reth/issues/11739

**Comment by steph-rs** [comment]
I'd love to take this

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:

We need to use the helpers introduced in https://github.com/paradigmxyz/reth/issues/11739. There is a similar open PR in Reth for this feature: https://github.com/paradigmxyz/reth/pull/11873

This would require a Reth bump on Odyssey.

**Comment by onbjerg** [comment]
Sorry @steph-rs, I'm going to have to take this over since it's P0 :( Hope you'll still consider contributing on another issue!
