### ISSUE TITLE
Add metrics for `wallet_` namespace

### ISSUE THREAD

**Issue by onbjerg** [ithacaxyz/odyssey#40]
It would be helpful to have the following metrics for the `wallet_` RPC namespace:

- Number of *invalid* calls to `wallet_sendTransaction` (i.e. where the request fails validation)
- Number of *valid* calls to `wallet_sendTransaction`

We can use `reth-metrics-derive`, just like we do in Reth.

**Comment by steph-rs** [comment]
since I saw [this](https://github.com/paradigmxyz/reth/pull/11335) PR, I used `metrics-derive` crate.
this is my first contribution here, so please let me know if anything is wrong.
