### ISSUE TITLE
Use quantity for chainid key type

### ISSUE THREAD

**Issue by mattsse** [ithacaxyz/odyssey#49]
this should serialize chainid as quantity (`U64`)

https://github.com/ithacaxyz/odyssey/blob/bc8c87e08ca07dfec3a6cc00bb0488c1e24248c4/crates/wallet/src/lib.rs#L60-L60

this could be made nicer if we had https://github.com/alloy-rs/alloy/issues/1502

but for now we need to use the `alloy-primitives::U64` type here instead of `u64`

## TODO
* use `U64` as the key type

**Comment by mattsse** [comment]
ah sorry my issue was vague, I was referring to serde here

```
HashMap<ChainId, Capabilities>
```

should serialize chainid keys as quantity (hex)

**Comment by 0xurb** [comment]
Should be useful to add “blocked” issue label to the labels list and point here maybe

**Comment by onbjerg** [comment]
it's not blocked

**Comment by 0xurb** [comment]
It’s awaiting quantity hashmap for alloy to put serde attribute on `WalletCapabilities`.

**Comment by 0xurb** [comment]
Oh, yes, my fault :)
