### ISSUE TITLE
include activation number in the revm_spec

### ISSUE THREAD

**Issue by malik672** [ithacaxyz/odyssey#58]
I've given this a lot of thought, currently we kinda random guess when it comes to the revm_spec function using an if/else statement, this is more optimized if the number of forks is small and the number of operations we do is small and let's assume we have more recent forks we are checking (this should be very true), that's why the initial check was from recent to oldest I guess)

if we include an activation number, we can leverage for times or conditions when we do not check for the most recent forks, leverage on numbers instead of checking each condition 

think of it this way, we are in a hotel, moving inside an elevator, we are going to the room at the top floor, but we don't know it yet, so we keep searching each room number from the lowest floor till we get to the one we want but what if we had the number of the room we wanted to go to we can simply just go there instead of checking each room for the one we want

we don't actually need to include an activation number or we might don't know tbh we can just need to label each one numerically from the oldest to the newest, using this we can optimize for the recent fork as well as the older one

of course we are still random guessing only now we don't have to search each rooms and we can just pick a section to search instead

**Comment by mattsse** [comment]
unclear what you're proposing here, but tracking the block activation numbers is a lot of extra work if the timestamp works similarly.

imo this conversion is fine
