### ISSUE TITLE
NFT Marketplace on Odyssey network

### ISSUE THREAD

**Issue by Visiok09** [ithacaxyz/odyssey#73]
Deployed Nft marketplace on Odyssey network
Contract address: https://odyssey-explorer.ithaca.xyz/address/0x991aB93a97964aD5AD4De67cd9C88a7c2C53e66a
Link to DApp: https://ithaca.alphamint.online/

**Comment by onbjerg** [comment]
This is not the right place to put this, this tracker is only for features and bugs:)
