### ISSUE TITLE
Installation fails on current `main` branch

### ISSUE THREAD

**Issue by zobront** [ithacaxyz/odyssey#89]
If you follow the instructions to install Odyssey from source using the current `main` branch:
```
git clone https://github.com/ithacaxyz/odyssey
cd odyssey
cargo install --path bin/odyssey
```
It fails with the following error:
```
error[E0603]: module `eip1559` is private
  --> /Users/zachobront/.cargo/git/checkouts/reth-36d3ea1d1152b20c/4b4f9cf/crates/optimism/payload/src/payload.rs:10:25
   |
10 | use op_alloy_consensus::eip1559::{decode_holocene_extra_data, EIP1559Par...
   |                         ^^^^^^^ private module
   |
note: the module `eip1559` is defined here
  --> /Users/zachobront/.cargo/registry/src/index.crates.io-6f17d22bba15001f/op-alloy-consensus-0.6.7/src/lib.rs:22:1
   |
22 | mod eip1559;
   | ^^^^^^^^^^^

error[E0603]: module `eip1559` is private
  --> /Users/zachobront/.cargo/git/checkouts/reth-36d3ea1d1152b20c/4b4f9cf/crates/optimism/payload/src/payload.rs:10:25
   |
10 | use op_alloy_consensus::eip1559::{decode_holocene_extra_data, EIP1559Par...
   |                         ^^^^^^^ private module
   |
help: consider importing this enum instead:
      op_alloy_consensus::EIP1559ParamError
  --> /Users/zachobront/.cargo/git/checkouts/reth-36d3ea1d1152b20c/4b4f9cf/crates/optimism/payload/src/payload.rs:10:63
   |
10 | ...code_holocene_extra_data, EIP1559ParamError};
   |                              ^^^^^^^^^^^^^^^^^
note: the module `eip1559` is defined here
  --> /Users/zachobront/.cargo/registry/src/index.crates.io-6f17d22bba15001f/op-alloy-consensus-0.6.7/src/lib.rs:22:1
   |
22 | mod eip1559;
   | ^^^^^^^^^^^

```
Everything works fine before the [latest commit](https://github.com/ithacaxyz/odyssey/commit/9c06a05e489992246af7a956d92543f10c46ee5b). It looks like bumping the version of `reth-optimism-payload-builder` pulls in the new `op-alloy-consensus`, which includes [this commit](https://github.com/alloy-rs/op-alloy/commit/cbac051d27b01fb85d1d628428a9ca8f9e9d9ad0) that re-exports the items from `eip1559` but makes the module itself private.

(Required as I'm trying to run a node with new reth features.)

**Comment by onbjerg** [comment]
Running this locally with a fresh copy of the repo works fine, is this a new clone or an older one with maybe an outdated lockfile?

**Comment by zobront** [comment]
@onbjerg Strange, I am running with a fresh copy. 

Digging into it a bit more, something is causing `op-alloy-consensus` to install version `0.6.8`, despite that the imported commit of reth only calls for `0.6.5`. I'll keep digging where the import is coming from and let you know.
