### ISSUE TITLE
Remove `wallet_getCapabilities`

### ISSUE THREAD

**Issue by onbjerg** [ithacaxyz/odyssey#99]
This is no longer used, so we can simplify quite a bit by just removing it. The only hurdle here is that we use it in e2e tests to get the delegation contract - however, any contract here will do, so we just need to adjust the tests to take e.g. an a contract address as an env var, or hardcode it.

**Comment by varun-doshi** [comment]
I cant take this

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:
